### PR TITLE
Fixing Code Snippet for GitHub Issue: 57033

### PR DESCRIPTION
**Pull request by AnuragSharma-MSFT**
## Purpose
Correcting the code snippet to include the variable 'message' as per the GitHub Issue #57033

## Does this introduce a breaking change?

```
[ ] Yes
[x ] No 
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet Build
dotnet Run
```

* Test the code
```
1. Insert the message using the newly available code
```

## What to Check
1. Do a peek on the newly inserted message on the Azure Storage queue

### CODE REVIEW

**Comment by AnuragSharma-MSFT** [comment]
Correcting the code snippet to include the variable 'message' as per the GitHub Issue #57033

@mhopkins-msft FYI

**Comment by KalyanChanumolu-MSFT** [comment]
[#57033](https://github.com/MicrosoftDocs/azure-docs/issues/57033)

**Comment by AnuragSharma-MSFT** [comment]
#sign-off

**Comment by AnuragSharma-MSFT** [comment]
@mhopkins-msft Could you please review and approve the PR?

I have made the changes as per the review provided by you.

**Comment by AnuragSharma-MSFT** [comment]
@mhopkins-msft Thanks for approving the changes. Could you please merge them or tag the appropriate person for the same?

**Comment by AnuragSharma-MSFT** [comment]
@mhopkins-msft Gentle reminder to merge the changes please.

**Pull request merged**
